### ISSUE TITLE
Analyzer.elements is not always an Array

### ISSUE THREAD

**Issue by justinfagnani** [PolymerLabs/hydrolysis#66]
It's initialized to `[]`, but later set to an Object keyed by element name.

**Comment by garlicnation** [comment]
That doesn't sound right. Where are you seeing this? elementsByTagName is an Object, and elements should always be an aray.

**Comment by nevir** [comment]
I think you're on an old build of hydrolysis - it used to be an object, but is no longer, and I snuck it into a patch revision cause I'm a jerk
